import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import 'style.css'
import Header from '../app/components/Navbar/Navbar'
import Footer from '../app/components/footer/Footer'
import Head from "next/head";



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Header />
        </header>
        <main>
          {children}
        </main>
        <footer>
          <Footer />
          </footer>
      </body>
    </html>
  )
}
